### ISSUE TITLE
Add an ArmIOSim implementation

### ISSUE THREAD

**Issue by n-arms** [Arctos6135/frc-2024#21]
This will require a lot of reading rather poorly written documentation, so good luck.

Use wpilib's [Single Jointed Arm Sim](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/simulation/SingleJointedArmSim.html) to create a simulation implementation of ArmIO. You should only need to set up the simulation using the constructor, call the `setInputVoltage` method when the voltage is set, and call the `update` method during the `updateInputs` call of `ArmIOSim`, similar to in `DrivetrainIOSim`.

The center of mass of the Arm is 0.35 m away from the pivot point, and the mass is [waiting on design].

**Comment by SomewhatMay** [comment]
Should be completed :)
