### ISSUE TITLE
Arm control scheme with feedforward + feedback + motion profiling

### ISSUE THREAD

**Issue by n-arms** [Arctos6135/frc-2024#23]
Make a command called `ArmPID` that controls the angle of the arm. It should use a combination of [motion profiles](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/trajectory/TrapezoidProfile.html), [feedforward](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/controller/ArmFeedforward.html), and [pid](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/controller/PIDController.html) to move the arm to a goal angle. The command should keep running even after the arm has reached its target to hold the arm in place.

**Comment by SomewhatMay** [comment]
Should be implemented properly! 

Update the constants for PID, feedforward, motion profiling, and voltages. 

Wpilib, if you're reading this, please stop naming your variables with prefixes and abbreviations...
![image](https://github.com/Arctos6135/frc-2024/assets/40745122/804ba49a-96b9-471a-8c5b-941bc6dd8988)
