### ISSUE TITLE
Add ShooterIOSim class

### ISSUE THREAD

**Issue by n-arms** [Arctos6135/frc-2024#28]
This will require a lot of reading rather poorly written documentation, so good luck.

Use wpilib's [FlywheelSim](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/wpilibj/simulation/FlywheelSim.html) to create a simulation implementation of `ShooterIO`. You should only need to set up the simulation using the constructor, call the `setInputVoltage` method when the voltage is set, and call the `update` method during the `updateInputs` call of `ShooterIOSim`, similar to in `DrivetrainIOSim`.

**Comment by joellekassir** [comment]
I'm not entirely sure how to commit to an issue, and I'd appreciate if someone could run through the code first. Thanks!
