### ISSUE TITLE
Write RobotContainer

### ISSUE THREAD

**Issue by n-arms** [Arctos6135/frc-2024#3]
A lot of this is similar (but not copy-pastable) from last year
- set up XBoxControllers
- add fields for / initialize subsystems
- set default commands

**Comment by Ayaanator** [comment]
I'm not sure how to set up the drivetrain and commands but I added the Xbox Controllers

**Comment by n-arms** [comment]
Looks good!

Try using `drivetrain.setDefaultCommand`to set up the TeleopDrive command. 

Also, the core idea behind AdvantageKit is to use `DrivetrainIOSparkMax` for when we are running code on the robot, and `DrivetrainIOSim` for when we are running simulation code. I'd recommend not making a `drivetrainIO` field in `RobotContainer`, and instead doing something like
```java
if (RobotBase.isReal()) {
    drivetrain = new Drivetrain(new DrivetrainIOSparkMax());
} else if (RobotBase.isSimulation()) {
    drivetrain = new Drivetrain(new DrivetrainIOSim()));
} else {
    drivetrain = new Drivetrain(new DrivetrainIO());
}
```
inside the constructor of `RobotContainer`

**Comment by SomewhatMay** [comment]
@n-arms 
What's the difference between `DrivetrainIO` and `DrivetrainIOSparkMax`?

**Comment by Ayaanator** [comment]
I finished. Does the container look good?
