### ISSUE TITLE
Add soft stops to the arm

### ISSUE THREAD

**Issue by n-arms** [Arctos6135/frc-2024#35]
We need soft stops on the arm so that we don't accidentally command it to try and push past the hard stop in the stowed position, or flip the robot over by going in the other direction. Since `ArmIOSim` has built-in soft stops, it makes sense to add the soft stops to `ArmIOSparkMax`. Luckily, `SparkMax`s have a built in tool to do this with the `SparkMax` onboard processor. Check out [this](https://codedocs.revrobotics.com/java/com/revrobotics/cansparkbase#setSoftLimit(com.revrobotics.CANSparkBase.SoftLimitDirection,float)) method.

**Comment by Rubinious** [comment]
I think soft stops have been added but someone should double check
