### ISSUE TITLE
Implement feedback + feedforward  control scheme for the drivetrain

### ISSUE THREAD

**Issue by n-arms** [Arctos6135/frc-2024#4]
Add a `setSpeeds` method that uses a combination of a `V = kS + kv v + ka a` feedforward controller and a PID controller for each side of the drivetrain to set the left and right speeds.

WPILib has classes for doing [PID](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/controller/PIDController.html) and [simple feedforward](https://github.wpilib.org/allwpilib/docs/release/java/edu/wpi/first/math/controller/SimpleMotorFeedforward.html).

**Comment by PouryaParsa** [comment]
To implement a setSpeeds method using a combination of a feedforward controller and a PID controller for each side of the drivetrain, you can create a class with methods for initializing and updating PID controllers, as well as the setSpeeds method.

**Comment by n-arms** [comment]
That's a very inspiring answer that I had not even considered, thank you for your insight. You are clearly an expert in control systems.

**Comment by SomewhatMay** [comment]
Should be added! @n-arms tuned the feedforward. PID might need some tuning.
