### ISSUE TITLE
Add a "ReverseFeed" command.

### ISSUE THREAD

**Issue by michewko** [Arctos6135/frc-2024#64]
An issue we saw at centennial was that once the note was fed into the shooter, our scoring options were locked in place, and we could only shoot amp. A reverse feed command will allow us to move the note from the shooter back into the intake, so we can switch to scoring speaker if needed. 

This command should be quite similar to the race feed command, only inverted. The command should require both the shooter and intake subsystem, and should be bound to an appropriate button on the operator controller.

**Comment by Rubinious** [comment]
has already been created
just needs to be tweaked
