### ISSUE TITLE
Implement feedforward + feedback control for shooter

### ISSUE THREAD

**Issue by n-arms** [Arctos6135/frc-2024#67]
Use a velocity based simple motor feedforward and a PID controller to run flywheel at a given speed. 

PID velocity loops for things that spin really fast are notoriously unstable. Try using the built in SparkMax PID methods to run the PID loop on the SparkMax itself instead of on the Rio (it'll be running at like 1kHz instead of 50 Hz), and take a look [here](https://www.chiefdelphi.com/t/psa-default-neo-sparkmax-velocity-readings-are-still-bad-for-flywheels/454453) for how to improve the default velocity filtering.

**Comment by BenM-BenM** [comment]
Created shooterPID command, just have to implement it in the correct places

**Comment by BenM-BenM** [comment]
Should be done
